# Generated by Django 3.0.14 on 2021-09-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210906_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='word',
            new_name='name',
        ),
    ]
