# Generated by Django 3.0.14 on 2021-09-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210906_2117'),
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='role',
            field=models.ManyToManyField(to='shop.Customer'),
        ),
    ]
